namespace Grove.Gameplay.Abilities
{
  public enum Static
  {
    Flying,
    Hexproof,
    Lifelink,
    Deathtouch,
    Trample,
    Haste,
    Fear,
    Unblockable,
    Indestructible,
    Defender,
    Shroud,
    FirstStrike,
    DoubleStrike,
    Reach,
    Vigilance,
    Swampwalk,
    CannotBlock,
    CannotAttack,
    Islandwalk,
    DoesNotUntap,
    Mountainwalk,
    AssignsDamageAsThoughItWasntBlocked,
    CanOnlyBeBlockedByCreaturesWithFlying,
    CanAttackOnlyIfDefenderHasIslands,
    Flash,
    AttacksEachTurnIfAble,
    UnblockableIfDedenderHasArtifacts,
    Forestwalk
  }
}